### ISSUE TITLE
Bad seeds path

### ISSUE THREAD

**Issue by arxeiss** [DrudgeRajen/voyager-deployment-orchestrator#18] opened 2019-09-21 20:54 UTC
Not sure what is wrong, but I had to change this line into `database/seeds/breads/`. Is it bug or I did something wrong?
https://github.com/DrudgeRajen/voyager-deployment-orchestrator/blob/76290f0959d6b222cbe212cfd4c98bd4acfb5722/publishable/database/seeds/VoyagerDeploymentOrchestratorSeeder.php#L10

When I tried to run seed, it said path does not exists

**Comment by DrudgeRajen** [comment] 2019-09-22 05:55
Did you publish the seeder file?  
`php artisan vendor:publish --provider="DrudgeRajen\VoyagerDeploymentOrchestrator\VoyagerDeploymentOrchestratorServiceProvider"`

**Comment by arxeiss** [comment] 2019-09-22 09:09
Yes I did. It creates file in databse/**seeds/breads/** but $seedersPath is database/**breads/seeds/** and then it doesn't work for me when seeding. All seeds are created, but not when running artisan command.

**Comment by DrudgeRajen** [comment] 2019-09-22 09:54
Would you please mention the version of  Laravel and voyager that you are using?

**Comment by arxeiss** [comment] 2019-09-22 11:51
Yes, sure:
Laravel 5.8.17
Voyager: 1.2.7
Orchestrator: v2.0.2

**Comment by DrudgeRajen** [comment] 2019-10-28 14:49
hi @arxeiss, I tried with the same version you mentioned but was not able to reproduce the error. Would you please share the error that you got?

**Comment by arxeiss** [comment] 2019-10-30 11:39
Hmm, acting weird now. In development it does not matter what is in `$seedersPath`. There can be whatever and it works. Will try to reproduce in production again. I think the problem was there only

**Comment by DrudgeRajen** [comment] 2019-10-30 14:30
If it works on production it should work in development as well. Please open the Issue again if you encounter this again. Closing for now. Thank you

**Closed as completed by DrudgeRajen** 2019-10-30 14:30 UTC
Labels: need to check
